SELECT deledocumento,delenombre,deleapellido,delenumero,delecorreo,deletelefono
FROM delegado 
WHERE deleactivo = 1
order by delenumero



INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','123456789','VOTO','BLANCO','99','NULL','NULL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','26774787','ADELINA ','NAVARRO BOHORQUEZ','1','adenabo21@gmail.com','3112535998', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','26777375','TORCOMA ','ANGARITA DUARTE','2','torcoromangarita@gmail.com','3176889267', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','26774702','ROSELIA ','GALVIS PACHECO','3','galvisroselia37@gmail.com','3152488620', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','1066063010','OSNEIDER ','CONTRERAS MENDOZA','4','ocontrerasm@ufpso.edu.co','3142744797', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','26777365','YEGNY BIBIANA','LOZANO ANGARITA','5','yeggny@gmail.com','3163586141', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','37182379','OLGA LUCIA','QUINTERO LOPEZ','6','olga.sha@hotmail.com','3132843300', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','1091654054','YAMILE ','SOLANO CASTRO','7','yamilesolanocastro12@gmail.com','3153081808', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','26777413','NELLY ','VARGAS PEÑARANDA','8','adrianchinchilla2305@gmail.com','3117239797', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','1733931','CARMEN ALONSO','TRILLOS SANCHEZ','9','mcarrascaltrillos@hotmail.com','3107929496', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','1007283563','DANIELA ','BOHORQUEZ MENESES','10','bohorquezd480@gmail.com','3138207516', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','26774858','ZORAIDA ','CONTRERAS MANZANO','11','sarayacon@yahoo.es','3164903472', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','77175658','CARMEN ANGEL','MADARIAGA MANZANO','12','caanmama@yahoo.es','3167250720', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','1003257534','CAROLINA ','GONZALES GUTIERREZ','13','carogogu09@hotmail.com','3125073770', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','26774951','SONIA ESTER','SANTIAGO CASTILLA','14','sonia_santiago2714@hotmail.com','3108700121', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','26777406','EDITH JOHANA','SANCHEZ BOHORQUEZ','15','edithbohorquez543@gmail.com','3124363200', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','1091653690','YULIETH PAOLA','PINZON GRANADOS','16','pinzongranados1986@outlook.com','3182743518', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','12435754','ALEJANDRO ','CARRASCAL GARCIA','17','alejocarrascal@gmail.com','3175910130', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','5035402','LUIS GERMAN','OSORIO OSORIO','18','osorioosorioluisgerman@gmail.com','3168662288', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','5458877','MARCO FIDEL','BAYONA RUEDAS','19','marcobayonaru@gmail.com','3186589047', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','26780600','DENIS MARIA','RUEDAS GARCIA','20','denisruedas61@gmail.com','3165033001', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','5035051','LUIS FERNANDO','QUINTERO DUARTE','21','fedoquin@hotmail.com','3165325209', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','13362393','JULIO HELI','GAONA MANZANO','22','22sincorreo@gmail.com','3135399947', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','49761164','PATRICIA DEL ROSARIO','GARCIA SANCHEZ','23','patolyn29@hotmail.com','3124805593', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','1007959718','EIDER JOHAN','CARRILLO CACERES','24','carrillo26eider@gmail.com','3178681582', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','26774663','MARIA NELLY','BOHORQUEZ DE SANTIAGO','25','manebosa@hotmail.com','3176201538', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','26777211','DORIS MARIA','SANTIAGO QUINTERO','26','dorissantiagoquintero@gmail.com','3143940586', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','5036072','ELIECER ','REYES ARIAS','27','eliecerreyesarias28@hotmail.com','3185783651', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','5035699','ADRIAN FELIPE','HORLANDY RIOS','28','adrianhorlandy1977@hotmail.com','3167822042', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','1066062899','MARTHA LORENA','AMAYA MOLINA','29','mlamayam@ufpso.edu.co','3107088421', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','26777273','OMAYDA ','TORREZ CARREÑO','30','omaydatoca04@gmail.com','3154822473', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','1003257672','YHON JAIRO','JACOME JACOME','31','jacomejacomejhonjairo04@gmail.com','3132486084', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','1066062810','HERNEY ','MANDON NAVARRO','32','hmandon92@gmail.com','3107713160', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','49782615','LILIANA DE JESUS','SANTANA SAUMETH','34','lilianasantanasaumeth1977@hotmail.com','3162446480', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','88279205','HUBERTH ','MOLINA MORA','35','sincorreo@hotmail.com','3178176278', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','5035439','JOSE ENCARNACION','DUARTE PORTILLO','36','joseeduarteportillo@gmail.com','3224567848', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','1066062762','HECTOR MANUEL','SANTIAGO RUEDAS','37','hmanuelsantiagor@gmail.com','3184247186', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','1091654839','KARINA ROCIO','BARBOSA CASTRO','38','karinarocca25@gmail.com','3168662112', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','5035339','EDGAR ','ASCANIO PEREZ','39','edgarascinio@gmail.com','3186118893', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','26777300','NANCY ','CARRASCAL NORIEGA','40','ncarrascalnoriega@gmail.com','3186383938', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','26777372','GISELA IRINA','ORTIZ ANGARITA','41','giselairina@hotmail.com','3167808831', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','26775063','OTILIA ','NAVARRO PICON','42','otilianavarro97@gmail.com','3153204558', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','26774838','LUISA TORCOROMA','OSORIO OSORIO','43','luisaosorio1966@hotmail.com','3175123571', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','26774947','CECILIA ','VERA SANTIAGO','44','ceciliavera71@hotmail.com','3213177046', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','88143184','NAUN ALEXANDER','MOLINA RINCON','45','naun.alex69@gmail.com','3112640044', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','5035242','LUIS EMIRO','DUARTE QUINTERO','46','ld6059439@gmail.com','3213547370', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','37329114','LUCIA ','CHINCHILLA CHINCHILLA','47','47sincorreo@gmail.com','3175061236', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','5036272','DEIMMAR ','DURAN PORTILLO','48','deimarduran470@gmail.com','3107036981', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','1978917','RAMON DAVID','SALAZAR RINCON','49','radasa10@hotmail.com','3204018506', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','26774708','TORCOROMA ','GARCIA DUARTE','50','torco64@gmail.com','3108707928', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','1091679273','INGRITH XIOMARA','MOLINA SANTIAGO','51','ingrithmolina@hotmail.com','3138774066', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','5036328','LIBARDO ALONSO','GALVIS SANCHEZ','52','galvizlibardo19@gmail.com','3172647928', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','1065124120','MARTHA MILENA','QUINTERO MENDOZA','53','marthamilenaquintero@gmail.com','3228965888', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO delegado(deleid,agenid,deledocumento,deleprimernombre,deleprimerapellido,delenumero,delecorreo,deletelefono,created_at,updated_at) VALUES (null, '1','1066062638','ALBEIRO ','TORRES CHINCHILLA','54','albeiro4@outlook.com','3107727052', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
